# .github/workflows/docs.yml
name: Generate Docs

on:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pdoc
        run: |
            pip install pdoc
            pip install tabulate
            pip install pandas

      - name: Generate documentation
        run: pdoc src -o docs

      - name: Push docs to repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs
          git commit -m "Update docs"
          git push